### ISSUE TITLE
DIsplay a hubspot form when needed on the blog

### ISSUE THREAD

**Issue by MartinRst** [kestra-io/docs#512]
### Feature description

Hey team! 

On the blog post, I can't use embed code from HubSpot to share a Form.

I would like to be able to display an embed form on the blog post when needed.

The form must be embedded like this one: 

 <script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "eu1",
    portalId: "27220195",
    formId: "e044de55-bda2-4bb8-9e50-ed8c78b94922"
  });
</script>

Not for all blog posts but when there is a purpose to share one.

Thanks!

**Comment by tchiotludo** [comment]
done in https://github.com/kestra-io/docs/pull/511

**Comment by MartinRst** [comment]
Still an Issue with the CTA display: 
<img width="1243" alt="image" src="https://github.com/kestra-io/docs/assets/125883179/8531ffdd-e693-4e97-926f-c9281b9f345e">
